//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Brumo\Documents\repos\Compiler-Design\Labs\Lab4\Compiler\bin\debug\netcoreapp3.1\ssupl.txt by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IssuplListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ssuplBaseListener : IssuplListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ssuplParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] ssuplParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ssuplParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] ssuplParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ssuplParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ssuplParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ssuplParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ssuplParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ssuplParser.braceblock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBraceblock([NotNull] ssuplParser.BraceblockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ssuplParser.braceblock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBraceblock([NotNull] ssuplParser.BraceblockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ssuplParser.stmts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmts([NotNull] ssuplParser.StmtsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ssuplParser.stmts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmts([NotNull] ssuplParser.StmtsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ssuplParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] ssuplParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ssuplParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] ssuplParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>condNoElse</c>
	/// labeled alternative in <see cref="ssuplParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondNoElse([NotNull] ssuplParser.CondNoElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>condNoElse</c>
	/// labeled alternative in <see cref="ssuplParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondNoElse([NotNull] ssuplParser.CondNoElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>condElse</c>
	/// labeled alternative in <see cref="ssuplParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondElse([NotNull] ssuplParser.CondElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>condElse</c>
	/// labeled alternative in <see cref="ssuplParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondElse([NotNull] ssuplParser.CondElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ssuplParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] ssuplParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ssuplParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] ssuplParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ssuplParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] ssuplParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ssuplParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] ssuplParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ssuplParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] ssuplParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ssuplParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] ssuplParser.ReturnStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ssuplParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop([NotNull] ssuplParser.LoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ssuplParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop([NotNull] ssuplParser.LoopContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
