//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Brumo\Documents\repos\Compiler-Design\Labs\Lab3\Lab3\\calc.txt by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="calcParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IcalcListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] calcParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] calcParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sumPlusFactor</c>
	/// labeled alternative in <see cref="calcParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSumPlusFactor([NotNull] calcParser.SumPlusFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sumPlusFactor</c>
	/// labeled alternative in <see cref="calcParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSumPlusFactor([NotNull] calcParser.SumPlusFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>sumToFactor</c>
	/// labeled alternative in <see cref="calcParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSumToFactor([NotNull] calcParser.SumToFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>sumToFactor</c>
	/// labeled alternative in <see cref="calcParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSumToFactor([NotNull] calcParser.SumToFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] calcParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] calcParser.FactorContext context);
}
